services:
  - type: web
    name: qualisense
    env: python
    plan: free
    
    # Chained commands (&&) are safer than pipe (|)
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    
    startCommand: "gunicorn qualisense_project.wsgi:application"